server:
  port: 9001
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka

kafka:
  bootstrapAddress: localhost:9092     
  topic:
    helloworld: helloworld.t
    json: json.t
    partitioned: partition.t


spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices?&serverTimezone=UTC
logging:
  file: /home/msa/logging/cloud-info.log